language: php
dist: trusty
sudo: required

cache:
    directories:
    - vendor
    - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - nightly
    - hhvm-nightly

matrix:
    fast_finish: true

notifications:
    email: false
    irc: "irc.iiens.net#Clicky"

before_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then sudo add-apt-repository ppa:ondrej/php -y; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then sudo apt-get update -q; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then sudo apt-get install libsodium-dev -y; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then pecl install libsodium; fi
    - rm -rf vendor/
    - rm composer.lock
    - composer self-update -n
    - composer install -n

script:
    - vendor/bin/phpunit --coverage-clover clover.xml
    - vendor/bin/phpcs

after_success:
    - composer require --dev satooshi/php-coveralls
    - travis_retry vendor/bin/coveralls -n -v
